### ISSUE TITLE
Extended/Additional Friends Groups.

### ISSUE THREAD

**Issue by ChillPenguinVR** [DubyaDude/RubyClientPublic#100]
There aren't enough Groups and slots in those groups in the base game for people who like to organize everyone (Especially by friends group). I think it would be useful to be able to make a system where people can easily add their own now groups through either the vrchat menu or through editing a text file.

**Comment by RubyYuukoShionji** [comment]
An alternative idea would be a tagging system, difference is vrchat itself only allows a user to appear in one group at a time. While a tagging system could be made to allow a user to have multiple tags

**Comment by ChillPenguinVR** [comment]
that is also a good way! there just needs to be more organization on the friendslist
