### ISSUE TITLE
Auto-Kick users with specific name from instance if master of instance

### ISSUE THREAD

**Issue by Windowsurfer** [DubyaDude/RubyClientPublic#101]
Main intend is to kick unwanted crashers before they can even try to crash anyone. Maybe even remember the user ID in the background to make even more sure.

**Comment by RubyYuukoShionji** [comment]
I get the intent of this is good hearthed but I'm afraid ppl will abuse this (for example making a list of everyone they don't like for petty reasons and instead not talking it out)
