### ISSUE TITLE
Disable Rotation for VR

### ISSUE THREAD

**Issue by KortyBoi** [DubyaDude/RubyClientPublic#105]
Non of Rotation works for VR. Please have it Disable for those using VR.
It could be as easy as an if statement
```
if (XRDevice.isPresent)
    noLoadRotation = true;
```

**Comment by Janni9009** [comment]
I believe unityXR is still almost completely stripped (with melonloader due to unhollower this gets unstripped but ruby doesnt use unhollower), so without unhollower they'd have to use a bool in (i think) vrctrackingmanager.

**Comment by KortyBoi** [comment]
Fair point. But however they can detect a VR device, I'd still like it to be Disable for VR at the very least.

**Comment by DubyaDude** [comment]
This is now in Movement.
