### ISSUE TITLE
Bot improvements

### ISSUE THREAD

**Issue by KeafyIsHere** [DubyaDude/RubyClientPublic#106]
a lot of people join ruby core asking how to buy ruby client and how to join the ruby client discord. It gets annoying have to tell them each time. so having 1 or 2 commands explaining how to buy and join will be nice

**Comment by RubyYuukoShionji** [comment]
If ppl don't wanna read the channel they ain't gonna use a bot. That's my two cents

**Comment by KeafyIsHere** [comment]
go back to studying for your exam tomorrow (I just want a bot to shame them truthfully)
