### ISSUE TITLE
Unpublished worlds savs

### ISSUE THREAD

**Issue by jaxjaxk** [DubyaDude/RubyClientPublic#107]
would be nice to save and load unpublished worlds. You know, because not all worlds are accessible by searching or made public. We know that it's already a way to save and load worlds by their ID but why not save them to a separate favorites list with their name?

**Comment by RubyYuukoShionji** [comment]
Im personally against this as if the world is unpublished its an indication the world author dont want their world to be accessable to the larger community. Having this feature would directly work against such a wish.

**Comment by jaxjaxk** [comment]
Yet the client allows you to get the world ID and go to worlds with the ID. Even without a client most people are easily capable of doing this with no modifications to the game. Why not make it easier?

**Comment by RubyYuukoShionji** [comment]
Re-emphasis on personally, its just my own thoughts.
