### ISSUE TITLE
Buttons to Respond to All Notifications

### ISSUE THREAD

**Issue by KuwuroUsagi** [DubyaDude/RubyClientPublic#11]
Buttons to do the following:

- Decline all active invites to other worlds
- Decline all active invites to join your world
- Reject all active friend requests
- Accept all active friend requests
- Reject all active votes to kick

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Base] Batch Notification Response](https://trello.com/c/K2bIXHTf/70-base-batch-notification-response)
