### ISSUE TITLE
Gravity issue

### ISSUE THREAD

**Issue by katzina00** [DubyaDude/RubyClientPublic#111]
When I put the gravity to far down and you start to fly, its kinda hard to stop.  So i suggest that you make it easyer to stop flying with gravity... Or that gravity cant make u fly up to the top of the world (aka forever).

**Comment by Murkur** [comment]
there used to be a button to rejoin a world through keybind that fixed this if anything I would recommend adding a keybind to reset movement modifiers back to default.

**Comment by DubyaDude** [comment]
A solution for this is now in Movement called QM Fly.
