### ISSUE TITLE
Clear Notifications

### ISSUE THREAD

**Issue by Murkur** [DubyaDude/RubyClientPublic#116]
Oh no your at a drinking party and your fps is 10 and you have thousands of old invites you cant see because the menu doesnt update thanks to low FPS|

TLDR add a button to the settings that allows clearing of your hud notifications like invites and friend requests

**Comment by KuwuroUsagi** [comment]
oh yeah I had something similar to this suggested back in the day, it'd still be a super nice QOL addition
![dgWavoP](https://user-images.githubusercontent.com/6632311/95842578-8d302780-0cfb-11eb-9d01-ab3d4a46bd16.png)

**Comment by DubyaDude** [comment]
Duplicate of https://github.com/DubyaDude/RubyClientPublic/issues/11
