### ISSUE TITLE
[Feature Request] Join/Leave logger. 

### ISSUE THREAD

**Issue by Dekotop** [DubyaDude/RubyClientPublic#117]
It would be nice to have the join/leave of other players logged into the command console. I want to know everyone who enters and leaves the world.

**Comment by Murkur** [comment]
This is already done with ruby moderations the full ruby log aswell as all moderation logs are at \vrchat\rubyclient\Logs
![image](https://user-images.githubusercontent.com/20288698/96591788-a31e8900-12b5-11eb-84b8-bae579e863f4.png)

**Comment by Dekotop** [comment]
👍
