### ISSUE TITLE
Global fix for Video Players

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#119]
Would be nice. I think global patch (for the room) would be possible? Sometimes they break or are not functional so this would be neat.

**Comment by jerk** [comment]
Well that's mainly master related and if the master of the room is not firing events probably it's probably not fixable unless the master is the person trying to fix the video player.

**Comment by DubyaDude** [comment]
As kronik has already stated, this mainly comes down to the master of the instance or comes down to how the video player is set up on the map. Unless proven otherwise I don't believe this can be implemented.
