### ISSUE TITLE
Paste Clipboard

### ISSUE THREAD

**Issue by KuwuroUsagi** [DubyaDude/RubyClientPublic#12]
Self explanatory, an easily accessible "paste clipboard" button for in-game usage.

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Core] Paste Clipboard button on VRC Keyboard](https://trello.com/c/gVYVoKQp/71-core-paste-clipboard-button-on-vrc-keyboard)
