### ISSUE TITLE
Control Client Buttons with Unity Parameters

### ISSUE THREAD

**Issue by Myrkie** [DubyaDude/RubyClientPublic#121]
Would be really cool to control RubyClient features like movement speed flight and stuff with a parameter in unity. Example being an avatar with a flight effect, flying with avatar using colliders suck ass so it would be very nice to control ruby flight speed gravity and rotation with a custom parameter.

**Comment by jerk** [comment]
custom parameter as in? Don't understand what you are trying to say.

**Comment by RubyYuukoShionji** [comment]
Pretty sure they meant something similar to SDK3's parameter driver, allowing ruby to be controlled from an animator.

**Comment by Murkur** [comment]
yeah with Yuuko said would be nice to drive ruby functions like flight with unity parameters in an animation like using vrcs parameter driver to adjust a parameter that will activate flight or disable it or increase speed to a set value
