### ISSUE TITLE
[Feature Request] Able to see who else is utilizing Ruby Client? #122

### ISSUE THREAD

**Issue by TheDiscordUser** [DubyaDude/RubyClientPublic#122]
subtle noticeable icon to be able to see who else is utilizing ruby client among OTHER ruby client users. :)))

**Comment by Murkur** [comment]
Declined will never happen dubbya has stated that customer privacy will be preserved

**Comment by jerk** [comment]
I'm sorry but that won't happen, plus it's better for peoples privacy.

**Comment by DubyaDude** [comment]
Already adressed [here](https://github.com/DubyaDude/RubyClientPublic/issues/36#issuecomment-572071056)
