### ISSUE TITLE
[Feature Request] Portal Notifications

### ISSUE THREAD

**Issue by BroPuter** [DubyaDude/RubyClientPublic#123]
Just a notification toggleable on and off for hud or console that shows that someone dropped a portal somewhere and who it was

**Comment by Murkur** [comment]
https://trello.com/c/AAUjIcEE/90-base-overall-portal-drop-notifier
https://trello.com/c/SCH8lUSG/91-worlds-portal-drop-history

**Comment by DubyaDude** [comment]
Duplicate
https://github.com/DubyaDude/RubyClientPublic/issues/42
https://github.com/DubyaDude/RubyClientPublic/issues/45
