### ISSUE TITLE
Better IK update rate

### ISSUE THREAD

**Issue by mvsmota** [DubyaDude/RubyClientPublic#125]
Before the IK update near the start of the year, there was a mod that would increase my IK update rate for others, making the fullbody dances way lot faster and more in sync. The new IK system that was implemented did fix a bit of that, making the IK update rate dynamic, the closer you are, the faster you move for others.

As a dancer, my request would be if its possible to bump that refresh rate a little bit more, as it seems that if you're a meter or two away from someone it already starts bumping down the refresh rate. Im not sure if its still possible to be done, since the dynamic IK now.

**Comment by jerk** [comment]
I'm not entirely sure if this can be done and attempting to do so could possible some server side anti abuse system. The update rate they have applied right now is probably as fast as the server will allow is what I'm trying to say.
