### ISSUE TITLE
[Feature Request] Avatar show/hide notifications

### ISSUE THREAD

**Issue by LordByronRS** [DubyaDude/RubyClientPublic#127]
I know that dub said that it needs more api requests, but vrcx also managed to do that and I never got banned for using vrcx. It's just uncomfortable to use. Maybe you could add it as a "probably risky" feature for those who wanna use it.

**Comment by Murkur** [comment]
avatar show hide notifications exist between you and other users its not possible between someone else and another user anymore as the API was changed and no longer broadcasts this information across the network instead moderation is pulling directly from https://api.vrchat.cloud/api/1/auth/user/playermoderations

**Comment by LordByronRS** [comment]
But would it be possible to finally integrate it in the moderation module?

**Comment by jerk** [comment]
it can but is probably not entirely practical

**Comment by DubyaDude** [comment]
Explained in further detail [here](https://github.com/DubyaDude/RubyClientPublic/issues/48#issuecomment-753489977)
