### ISSUE TITLE
UI Rank Font Color 

### ISSUE THREAD

**Issue by Meeran1675** [DubyaDude/RubyClientPublic#129]
Since VRChat updated their UI, I was hoping Ruby could implement a feature that would color the font of people's names based on their rank, like how it used to be. Names are already yellow for friends, so why not for the other ranks?

**Comment by MinerSpark** [comment]
If this dare gets implemented, make it toggleable default being off.

**Comment by jerk** [comment]
Pretty plausible suggestion.

**Comment by DubyaDude** [comment]
of course, the default would be closest to vanilla VRC as possible, so yea it would defaultly be off :)
