### ISSUE TITLE
Integrated Playspace Mover for non FBT

### ISSUE THREAD

**Issue by LucianUsagi** [DubyaDude/RubyClientPublic#13]
Not everyone has full-body tracking and instead uses [Playspace Mover](https://github.com/naelstrof/VRPlayspaceMover).
It would be a nice quality of life addition to bundle playspace mover with the Base Module, so that players don't have to open up the playspace mover manually.

**Comment by DubyaDude** [comment]
I agree with everything besides this being in Base, would fit better in Movement

**Comment by DubyaDude** [comment]
Decided this is something I'd rather not do, that being bundling someone else's code into a module. A user can easily create a batch file that opens VRC and Playspace Mover
