### ISSUE TITLE
Auto converting join links to world ID

### ISSUE THREAD

**Issue by Murkur** [DubyaDude/RubyClientPublic#135]
Update Join world by ID to support Https links or auto convert them to room ids so you can use a join link from vrchat.net or vrcx

**Comment by DubyaDude** [comment]
Can I get examples? I believe join by WorldID already does this parsing.

**Comment by Murkur** [comment]
When getting a join ID from VRCX like an invite it always comes with HTTPS join from the vrchat.net link
so an example being 
https://vrchat.net/launch?worldId=wrld_4cf554b4-430c-4f8f-b53e-1f294eed230b&instanceId=23397~hidden(usr_ecbc7683-d6a8-465f-8853-2ceac5aa9c44)~nonce(D2E8768A8C39972E8F30F2CFE1667ABB899E75149B963685A5578FAFAF606C17)

for this to work for ruby it would have to be edited like this
wrld_4cf554b4-430c-4f8f-b53e-1f294eed230b:23397~hidden(usr_ecbc7683-d6a8-465f-8853-2ceac5aa9c44)~nonce(D2E8768A8C39972E8F30F2CFE1667ABB899E75149B963685A5578FAFAF606C17)

removing both t he HTTPS link and the &instanceId= from it for ruby to parse it as a valid invite WorldID

**Comment by DubyaDude** [comment]
Tested this in clipboard
https://vrchat.net/launch?worldId=wrld_4cf554b4-430c-4f8f-b53e-1f294eed230b&instanceId=23397~hidden(usr_ecbc7683-d6a8-465f-8853-2ceac5aa9c44)~nonce(D2E8768A8C39972E8F30F2CFE1667ABB899E75149B963685A5578FAFAF606C17)

Was pushed into this world when clicking Join By WorldID
wrld_4cf554b4-430c-4f8f-b53e-1f294eed230b:23397~hidden(usr_ecbc7683-d6a8-465f-8853-2ceac5aa9c44)~nonce(D2E8768A8C39972E8F30F2CFE1667ABB899E75149B963685A5578FAFAF606C17)

**Comment by DubyaDude** [comment]
AH WAIT, nvm i see the issue.

**Comment by Murkur** [comment]
yush it just needs to remove the extra parts of the invite link

**Comment by DubyaDude** [comment]
Wait, no I'm right, the world gets parsed correctly.
![chrome_5jj2wCY9QA](https://user-images.githubusercontent.com/13679909/105748237-d9e8e880-5f0f-11eb-8cf9-0bdb9f4a6c64.png)

**Comment by DubyaDude** [comment]
Seems to be a bug, but the user was not able to recreate.
Might have to do with W10 Clipboard History?
