### ISSUE TITLE
Something for beta

### ISSUE THREAD

**Issue by katzina00** [DubyaDude/RubyClientPublic#137]
Make it so that you can search for avatars. Like if u search rainbow. U get avatars with rainbow name or something. Or if u search NSFW u get avatars with NSFW. Stuff like that could be usefull.

**Comment by Murkur** [comment]
avatar searching is not as simple as it sounds it requires an avatar database, dubbya acquired a database over a year ago but will take some time to implement.

**Comment by DubyaDude** [comment]
Duplicate of https://github.com/DubyaDude/RubyClientPublic/issues/31
