### ISSUE TITLE
Ruby UI Toggle

### ISSUE THREAD

**Issue by WiFiCo** [DubyaDude/RubyClientPublic#138]
This request has popped up a few times over the years, but there doesn't seem to be a formal suggestion.

Would like a toggle for at least some Ruby UI elements (ie ruby menu/settings menu/avatar and world options) if not all, with a toggle to switch it back on under the UI section of the quick menu.
Would benefit anyone who want to use ruby for security, optimization, and administrative capabilities when either putting on a presentation, hosting an IRL get together, or when using conflicting tools which have overlapping menu items.

**Comment by DubyaDude** [comment]
This is now possible with the quick menu icons with the introduction of Tabs where the UIType can be set for all modules, essentially 'hiding ruby UI'. 
This does not however cover avatar lists and social menu buttons/user buttons, so I will keep this open
