### ISSUE TITLE
Better Configs

### ISSUE THREAD

**Issue by Murkur** [DubyaDude/RubyClientPublic#14]
Option to relocate all config and json/txt files created by ruby to another directory so all avatar favorite txt files as well as all designer configs so we can save them in another directory or a network drive 

Suggested tags (item:avatar type:suggestion item:core item:designer)

**Comment by DubyaDude** [comment]
I was thinking about moving all the data to AppData directory to allow sync between oculus and steam versions of the game. Or would you rather want it fully customizable?

**Comment by Murkur** [comment]
> I was thinking about moving all the data to AppData directory to allow sync between oculus and steam versions of the game. Or would you rather want it fully customizable?

fully customization would be good means people can put it anywhere like on a second drive im going to throw mine onto my network drive since its always on and is never touched

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Core] Ruby Config/Cache File Management](https://trello.com/c/Rp1bplRY/72-core-ruby-config-cache-file-management)

**Comment by Murkur** [comment]
close because old post already done
