### ISSUE TITLE
Bug report: Clipping distance doesn't stay set after world change

### ISSUE THREAD

**Issue by MinerSpark** [DubyaDude/RubyClientPublic#140]
Step to redo:
have default clipping distance enabled
check its on by having your hand clip your face and then check with min clip
Return to default clip and then change world and setting will show it on default but have min clipping setting in effect.

**Comment by DubyaDude** [comment]
I think this may not really be a bug, but just an issue with how we handle the default near clip. We don't actually reset it to its previous value, we just set it to 0.05f. So that's probably greater than what the world originally had. This can be easily updated/fixed.

**Comment by MinerSpark** [comment]
Ah, I see how its applied.
Didn't think of it in this way, i assumed it used the worlds default, but the defaullt in ruby is static, so it resets to ruby's default.
Gotcha, so yeah, its not a bug, I just didn't think indepth about it.

I'd say its fine to remain, it just confused me while i was working on my world, thought my cliping distance was broken/not responding.

Close If you feel necessary.

**Comment by Murkur** [comment]
Knah recently released a viewpoint tweaker you could take a look at and see if its justt you https://github.com/knah/VRCMods/releases/download/updates-2021-01-30/ViewPointTweaker.dll

**Comment by DubyaDude** [comment]
> Ah, I see how its applied.
> Didn't think of it in this way, i assumed it used the worlds default, but the defaullt in ruby is static, so it resets to ruby's default.
> Gotcha, so yeah, its not a bug, I just didn't think indepth about it.
> 
> I'd say its fine to remain, it just confused me while i was working on my world, thought my cliping distance was broken/not responding.
> 
> Close If you feel necessary.

It's a fairly simple fix, we're just focused on the VRC-Beta rn so we'll fix this after.

> Knah recently released a viewpoint tweaker you could take a look at and see if its justt you https://github.com/knah/VRCMods/releases/download/updates-2021-01-30/ViewPointTweaker.dll

No need, it's a fairly easy fix on our end.

**Comment by DubyaDude** [comment]
This fix has been coded and will be added next update.
Thank you for your patience
