### ISSUE TITLE
Add Notifications to New Notification Menu in the Quick Menu

### ISSUE THREAD

**Issue by loukylor** [DubyaDude/RubyClientPublic#141]
It would be nice if you could push notifications to the Quick Menu rather than the HUD:

1. seeing as they stay their longer than 3 seconds
2. they're far less in your face 
3. and if you get a lot at a time you won't be seeing text on your HUD for a long time

Anyways, keep up the good work Ruby Team, your efforts do not go underappreciated!

**Comment by Murkur** [comment]
if you select the notification it brings you to the new quickmenu notification UI after that it will be hidden from the QM
