### ISSUE TITLE
Better FBT Calibration item:base type:suggestion

### ISSUE THREAD

**Issue by S1rM4ngi** [DubyaDude/RubyClientPublic#143]
i have seen this on an other client and i think this would be fairly easy to implement, for FBT calibration having an additional orb for where the viewpoint is, making it easier to get the viewpoint right. This is just a small feature that really helped me out a lot while using it.

**Comment by TheDiscordUser** [comment]
I like this request. It makes me really upset that VRChat doesn't already do this.

**Comment by Murkur** [comment]
> i have seen this on an other client and i think this would be fairly easy to implement, for FBT calibration having an additional orb for where the viewpoint is, making it easier to get the viewpoint right. This is just a small feature that really helped me out a lot while using it.

really not point for Ruby to have this when using new calibration method it automatically lines your viewpoint up with your headset and thats why it moves with your avatar and using a mod by Knah IKTWeaks allows you to freeze the avatars position when you hold the trigger on one controller.
