### ISSUE TITLE
Tabs on the top border of the QM instead of the borders?

### ISSUE THREAD

**Issue by ghost** [DubyaDude/RubyClientPublic#144]
Literally that's the free space where they should be..

**Comment by RubyYuukoShionji** [comment]
vrc+ and notifications are there, also imo there wouldnt be enough space.

**Comment by DubyaDude** [comment]
> vrc+ and notifications are there, also imo there wouldnt be enough space.

Didn't we literally already talk about this between us???
A. Move VRC+ items up, pretty sure they have their own collider so it's not really a pain
B. Yes there is, just shorten the tabs along the menu and make it taller. In math terms take the current Ruby tabs and rotate it 90 degrees.
