### ISSUE TITLE
[Bug] ESP Disabled after world change

### ISSUE THREAD

**Issue by MinerSpark** [DubyaDude/RubyClientPublic#145]
Rebuild:
goto buzy world
turn on esp
change world
esp toggled on but no capsules, they reapper after rejoin.
edit:
applys to any world change or rejoin

**Comment by DubyaDude** [comment]
It's a bit vague but what I'm getting at is

> Toggle ESP
> Join a new world
> ESP no work until rejoin

If so I'm unable to recreate it

**Comment by MinerSpark** [comment]
Visual demo: https://cdn.discordapp.com/attachments/402522901255028739/809589121982005248/2021-02-12_00-56-41.mp4

**Comment by DubyaDude** [comment]
Ok, so issue occurs upon world rejoin
I'm still not able to recreate this on my end, I'll ask my other staff to test it out

**Comment by DubyaDude** [comment]
With 3 test subjects, I was unable to recreate the issue at all.

**Comment by MinerSpark** [comment]
Restarted game, Don't have the issue anymore, might be tempermental(?) feel free to close.
