### ISSUE TITLE
[Feature Requests] List of some feature recommendations?

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#146]
Fixes: 
- social menu no longer causing you to be stuck in place sometimes and require a restart of your game (i had to restart like 4 times today pls help)
- action menu access for stuff like rejoin world, force quit, etc for cases which game bugs
- quick menu fly no longer causing fly to stay on after menu closes

Base: 
- Keybinds for desktop/shortcuts for VR (for things like movement and whatnot) to enable smooth use of features
- More convenient way to quicker use some things in the moment ^
- Instant join last instance after crash (toggleable) 
- Quick menu attach to hand, can use while moving
- Social menu adjusts to current position, so can be used comfortably in VR and prevent social menu bugging
- Third person / Free view camera
- Pickup from infinite distance (?) / Better pickup (could be for Worlds)
- Object manipulation (?) in some ways, i dunno (could be for Worlds)
- Ability to see original names of users after a recent name change / button to check in social menu
- Username text appears in color of trust ranks (toggleable) 
- Hide unnecessary things that can take toll on fps when it is not needed to be rendered at a given time (idk if this is what vrc does by default but just putting it out there)
- Reconnect to lobby you were in, if VRChat decided to time out (someway to limit this possibly too? dunno)
- Return to same scrolling position in the social/worlds menu after pressing a world/person and pressing back 

Microphone:
- Silly filters

Moderation:
- FPS / Ping counter for other players
- List of people in the lobby
- Instance master tracker
- Debug menu attach to hand / pickup
- noblock seems not to work in my experience, could be broken

Movement:
- Float
- Run on walls (if this is possible that would be cool as hell lmaoo)
- Fake lag (?) maybe could use emmvrc's toggles so it doesn't work for game worlds
- Slider so adjustments can be made in between increments
- Slow motion effect
- When resetting movement speed, reset to the default speed of the world you are in
- Click to teleport
- Double tap to speed up

Misc (idk type features): 
- Orbit (?) maybe using emmvrc's toggles so it doesn't work for game worlds 
- Serialize (?) maybe using emmvrc's toggles so it doesn't work for game worlds
- Dispense emojis faster / in more quantity lmao, something silly with it
- Looping of emotes? 
- Ability to use emotes while moving for cases that it is canceled 
- Hide menu sections / customize social menu
- Make small camera buttons easier to press

Avatar:
- Avatar search
- Fix for thumbnails disappearing / not loading for avatars favorited via ruby
- Option to close list of public avatars by an author after it is shown up (currently, it stays)

Worlds: Instance History, Player History, Ability to drop portals despite how close to spawn

These are just a lot of random ideas I thought would be convenient or fun to have. Maybe could serve as some inspo for some ideas and whatnot! Make ruby op (but still wholesome)?

**Comment by RubyYuukoShionji** [comment]
thanks for all the suggestions, but please make a separate issue per suggestion, its alot easier for us to track and work with then.

closing and marking as invalid, please repost as separate suggestions.
