### ISSUE TITLE
Reload Current World Button [Loading Screen] [UI] [IMG Attatched]

### ISSUE THREAD

**Issue by TheDiscordUser** [DubyaDude/RubyClientPublic#147]
Today as of now, by Default when you enter a portal in the game there is a "Go!" button or a "Return to Home" OR  "Go to default Home" button . 

**Feature Suggestion: Add an extra button to "reload current instance".**
You may ask, why add something that already exists in the 2D UI? Well this is in case you get portal dropped or you went in the wrong portal by mistake. You can't use the 2D UI if you're ALREADY in the loading screen. I've been getting a lot of "timed out" or "token lost" screens for sitting in a world for too long. This is nice to have because its convenient for transitioning between worlds. This is a must have in my opinion but i cannot speak on behalf of others.

![Attatchment](https://user-images.githubusercontent.com/75543858/108764410-6a164f80-7507-11eb-8ecd-eb90c3271da9.gif)

**Comment by Murkur** [comment]
This used to be a feature in the previous version of ruby in il2cpp but seems to have not made a return yet I would like this returned aswell

**Comment by TheDiscordUser** [comment]
Hopefully the example image isn't too confusing. The 2 images on the right are an example of reloading a world. The much larger image in the middle is an example of how it could be used as a button.

**Comment by Murkur** [comment]
for old ruby that made it work in a different way you still had the default return to home button but pressing it once would reload the world pressing it a again would return to home.

**Comment by RubyYuukoShionji** [comment]
Personally i think it makes more sense for this to be a "Go to previous world" not a "Reload current world", beacuse when you are in the loading screen you have already changed the world you are in.

But i think (unless you are kicked ofc) having a button on the screen taking you to your last non homeworld would be a good feature.

An alternative would be the old behaviour where if you crashed, youd always just join back to the last instance you were in.
