### ISSUE TITLE
Automatic blocking for yoinkers

### ISSUE THREAD

**Issue by Murkur** [DubyaDude/RubyClientPublic#15]
automatic blocking option for people who are listened as Yonkers on Bully-Hunters-v3

Suggested tags (item:base)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Base] Yoinker Detector](https://trello.com/c/KDQZCfk3/8-base-yoinker-detector)

**Comment by DubyaDude** [comment]
Yoinker Detector is no longer a feature, and I don't have too many plans on bringing it back, and here's my reasoning why:

When the updated yoinker got 'dropped' by you know who, he basically left the game right after. This allowed many skids to just copy and paste into their client, many of them leaving it untouched. This made it easy to maintain and expand the Yoinker Detection system to cover the ground it did.

Currently, Re-uploader is completely different. It's closed source and is being constantly improved upon. Fighting something like this is useless, as you push more detection methods the devs of ReUploader improve and eventually reach 'perfection' to the point where it becomes completely undetectable. I do not wish to be involved in a race like such just for the possibility of when it eventually goes 'down' I want it to be in the imperfect state that allowed the original Yoinker Detector to thrive.

If we do ever get to that point, I will re-open this.
