### ISSUE TITLE
[Feature Request] Ease of access for movement features 

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#150]
A keybinding system for desktop / VR would be nice to have. I think currently navigating through the tabs and menus in order to enable / disable things isn't that convenient. 
- It would be nice to be able to map some features to buttons
- Possibly a customizable selection system that can be accessed easier for easy use of different movement features for both VR and desktop mode ?

**Comment by DubyaDude** [comment]
Merging with #64
