### ISSUE TITLE
Better User Identification

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#151]
With the nametag UI overhaul, the only way to view ranks of other users is to have the quick menu open. 
- It would be nice to be able to identify trust ranks by color of the username text.
- Ability to see original names of users after a recent name change (perhaps next to their name based on if the name change is recent)
- Button in social menu to view previous names of a user

**Comment by Tritn-cmd** [comment]
As far as I know, you can't see all previous names of users. You can only see their Display name and Username.

**Comment by Murkur** [comment]
@Tritn-cmd that's correct you can only see there first set name and the current one only way to see previous names is by logging them for changes.

**Comment by DubyaDude** [comment]
Nameplate colors already exist in the [Trello](https://trello.com/c/AyeYqrq8/41-designer-nameplate-colors) from a previous module (PRE-IL2CPP).
Previous names are not possible. What you may be referring to is the Username (in contrast to the DisplayName).
