### ISSUE TITLE
Better Pickup / Object Interaction

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#152]
Objects can be sometimes buggy with their interaction distance and be a hassle to pickup and interact with sometimes.
I suggest:
- Pickup from infinite distance
- Better pickup (easier / improved detection when hovering over items)
- Perhaps a way to manipulate objects in different ways, other than the standard grabbing and throwing of objects. 
- ^ There could be some limits placed on this so that it cannot be abused maliciously, but it would be nice to be able to manipulate objects in a world

**Comment by Murkur** [comment]
3. vrchat allows native rotation of picked up objects awhile ago 
![image](https://user-images.githubusercontent.com/20288698/108885074-5afdd300-75d5-11eb-9778-d59dd7dbfae7.png)

**Comment by DubyaDude** [comment]
1. I simply don't see a need for this, in fact, I feel most people would find infinite distance pickups rather annoying.
2. That isn't an issue ruby can really work on, that is up to the person that made the object to create it properly.
3. Myrkur already beat me to that

**Comment by Murkur** [comment]
1. don't you love it when your sitting down or talking to someone and then randomly that stupid FUCKOFF pillow randomly zooms into your hands because your using index controllers? fucking fantastic.
