### ISSUE TITLE
[Feature Request] Better Moderation (Lobby list, FPS / Ping of other users, Instance Master, etc)

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#156]
- FPS / Ping counter for other players
- List of people in the lobby
- Instance master tracker
- Debug menu attach to hand / pickup (or console)
Honorable mention: 
- noblock seems not to work in my experience, could be broken

**Comment by Murkur** [comment]
First and second and third one is a duplicate of [issue 134](https://github.com/DubyaDude/RubyClientPublic/issues/134) and yes noblock is very much broken as seen from reports and testing by users.

**Comment by DubyaDude** [comment]
First and Second is duplicate of #134, Third is a duplicate of #94
And Yes, I am aware and am working on the fourth one
