### ISSUE TITLE
[Feature Request] Misc Features (Orbit, Serialize, Fake Lag)

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#159]
I think it would be nice to have these more sort of silly features to be able to mess and play around with.
These are features that could possibly have limits like emmvrc's game world checker so that it isn't abused maliciously, and are generally just more silly features that gives freedom to mess around.
Here is my proposal:
- Orbit (similar to OG Ruby orbit, perhaps with tweaks)
- Serialize. I think this can have a fair use, sometimes, which could just be to sort of save your position and move around. Locally could also help prevent targeting of other users, etc. 
- Fake lag. I think this wouldn't be that malicious in most context. Pretty self-explanatory. What this would do is just delay movements / voice input and could make you appear as if you are laggy. It could have position displacements and etc. 

^ These, if were to be incorporated to some extents, could be implemented into keybinds / selection system to make them easy to use at a given time for both VR and desktop.

**Comment by DubyaDude** [comment]
Firstly, I'm not into the whole 'limit by which world your in' aspect. It's either available or not.
I'm not adding back Orbit cause it's been abused in the past to the point where I started getting harassment reports.
Second I don't even understand what the suggestion is.
Third sure, however, this assortment of requests are in no way alike to let this stay up, so I'm closing this for the reason of multiple feature requests in one.
