### ISSUE TITLE
Unity 2018 Support

### ISSUE THREAD

**Issue by yamiM0NSTER** [DubyaDude/RubyClientPublic#16]
With inevitable update comming and my client being highly dependent on stuff that will no longer exist, I'd like to at least have a worthy replacement ready.

XoXo Dubby <3

**Comment by DubyaDude** [comment]
TLDR: It's being worked on, might not be ready for the update but we will do our best ^-^
![Discord_2L4NEltn8Q](https://user-images.githubusercontent.com/13679909/68998075-8266db80-087b-11ea-9dfd-7e7d307793bc.png)

**Comment by DubyaDude** [comment]
Cleaning up suggestions will mark this as complete as certain (not all) parts have been ported. Stay up to date through the discord and Trello as we will be re-releasing the next module within the very near future.
