### ISSUE TITLE
Emoji Manipulation

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#160]
It would be pretty silly, but if possible, perhaps a way to:
- Dispense emojis faster
- Dispense emojis in larger quantity
- Size of the emojis (?)
- Distance of the emojis (?)
- Different ways to control or loop emojis

This is really just a fun one, don't think it would harm much, but would be pretty cool.

**Comment by Tritn-cmd** [comment]
All of that will work locally from what I know except for the loop.

**Comment by DubyaDude** [comment]
I don't particularly see the point of doing this just locally
Not only that but the EmojiRPC has been abused time and time again for lagging/crashing other users. I would be personally uncomfortable having a tool like that in case they do put harder restrictions on emoji spamming, thus ban wave
