### ISSUE TITLE
[Feature Request] Drop portals near spawn

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#161]
Some worlds have a pretty big spawn, and it is annoying to reopen your menu and refind the world you wanted to drop a portal to. Would be nice if you are able to drop a portal close to spawn and ignore that check.

**Comment by Tritn-cmd** [comment]
That can be used in malicious ways so I don't know about that one.

**Comment by DubyaDude** [comment]
^
We don't do malicious things, there is obviously a good reason why that limitation exists
