### ISSUE TITLE
[Feature Request] Optimization

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#164]
- Hide unnecessary things that can take toll on fps when it is not needed to be rendered at a given time (idk if this is what vrc does by default but just putting it out there)

Perhaps there are some other ways to improve VRC performance, it already has lately with the recent updates, but just throwing it out there.

**Comment by Murkur** [comment]
Could be done mods do exist that hide avatars once they have gone to far away from you.

**Comment by DubyaDude** [comment]
Too vague of a suggestion.
