### ISSUE TITLE
Instance History 

### ISSUE THREAD

**Issue by Grobitalks** [DubyaDude/RubyClientPublic#167]
[Feature Request] A instance history would be nice (simmilar to the one emm has) Since i wana get rid of emm

**Comment by Murkur** [comment]
its already been suggested and is in TO DO 
https://trello.com/c/FSR31Iqx/81-worlds-history-pins
https://trello.com/c/rK93iBiU/16-worlds-world-history

**Comment by Grobitalks** [comment]
Thank you i am blind
