### ISSUE TITLE
Do a flip on spawn ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by GhostYiL** [DubyaDude/RubyClientPublic#17]
Just do a flip at spawn yeah..Flips are coool YEEEEAH ( ͡° ͜ʖ ͡°)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Base] Do a flip on spawn ( ͡° ͜ʖ ͡°)](https://trello.com/c/QvIzAHhY/73-base-do-a-flip-on-spawn-%CD%A1-%CD%9C%CA%96-%CD%A1)

**Comment by DubyaDude** [comment]
Was 10/10 meme, just closing it because I'm planning on starting to work on some of these <3
