### ISSUE TITLE
Disable full-body

### ISSUE THREAD

**Issue by Myrkie** [DubyaDude/RubyClientPublic#18]
Button within ruby avatar that will allow disabling full-body calibration so you can continue like a normal VR user for scuffed avatars that dont support full-body

(Suggested Tags:item:avatar)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Avatar] Disable FullBody Calibration](https://trello.com/c/KzPIFvV9/74-avatar-disable-fullbody-calibration)
