### ISSUE TITLE
Avatar preview

### ISSUE THREAD

**Issue by fwenny** [DubyaDude/RubyClientPublic#20]
Would love an improved avatar preview to what vrchat does in the avatar menu for the selected avatar.

Instead of having it stand there and slowly rotate, maybe make it static and give us free control to rotate it and maybe zoom in/out to check details we cant normal see (like the back of the avatar).

Another way to do this is spawn the 3d model in front of us so we can move around it and look at it as if it was another user who is currently using the avatar.

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Avatar] Better avatar preview](https://trello.com/c/Mh5ioj15/75-avatar-better-avatar-preview)

**Comment by fwenny** [comment]
Leads to an error page.

**Comment by DubyaDude** [comment]
Trello page is currently private until further notice
