### ISSUE TITLE
In social list, have additional icons

### ISSUE THREAD

**Issue by fwenny** [DubyaDude/RubyClientPublic#22]
The icons would tell us if the user is currently in private / f / f+ / pub.

Also an ability to filter out users who are currently in private from the list.

**Comment by DubyaDude** [comment]
Not sure exactly what module I would put this in, possibly that upcoming IRC (might rename to social), for now just adding it to IRC

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Unknown] Additional icons in social list](https://trello.com/c/CPQoK4si/76-unknown-additional-icons-in-social-list)
