### ISSUE TITLE
Download world in background

### ISSUE THREAD

**Issue by fwenny** [DubyaDude/RubyClientPublic#23]
Instead of going to the loading screen waiting for map to be downloaded, have it be downloaded in the background and then have a notification for when the DL is complete.

This is already possible by going to the loading screen of a new world, clicking "Go Back", waiting for the map to dl, but a more streamlined way of doing this would be great.

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Worlds] Background world downloading](https://trello.com/c/92DLqUkh/78-worlds-background-world-downloading)
