### ISSUE TITLE
Instance History Pins

### ISSUE THREAD

**Issue by KuwuroUsagi** [DubyaDude/RubyClientPublic#25]
Allow an instance to be pinned and take up 1 of the last slots in the World History window. For those nights where you're hopping around but want to get back to your main world a bit easier without too much hunting. Could also be unpinned, ofc.

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Worlds] History Pins](https://trello.com/c/FSR31Iqx/81-worlds-history-pins)
