### ISSUE TITLE
Additional Project column for Ruby 4.0 to show future plans

### ISSUE THREAD

**Issue by LucianUsagi** [DubyaDude/RubyClientPublic#26]
There's "currently working on" and "finished" columns. Would be nice to see perhaps a "Plans for later" column people could check up on to see what can be expected after the rewrite.
Also creates a nice space for dev approved suggestions, away from community approved ones.

**Comment by DubyaDude** [comment]
My plan is to completely remove "Future Plans" as the reason for that in the first place was the immense amount of disorganization the discord had in #ruby-suggestions channel.

It'll then be replaced with a "In the near future" column on the project page with the webhook posting changes through the discord.

However, currently I'm still not 100% sure about the future state of ruby, but a major stride was made today in one of our testings that may help us port ruby with much ease. 
However, I still plan to remake a decent part of ruby as this is a good time for us to clean up code that is in much need of cleaning.

**Comment by DubyaDude** [comment]
Column "In the near future" added. Don't expect too many updates on that at the moment as a lot of development currently going on is on the loader end, that of which Ruby is not completely involved in.
