### ISSUE TITLE
Bring back PC/Quest icon for Avatars/Worlds

### ISSUE THREAD

**Issue by KortyBoi** [DubyaDude/RubyClientPublic#27]
I can’t speak for everyone here, but I mainly play with Quest users (tend to be more wholesome) and ever since the compatibility icon was removed, I can never tell if an avatar or world is Quest compatible. 
Even if you could make this a toggle and save by config, that’d be great.

- it can even be toggled off by default.

**Comment by DubyaDude** [comment]
This is more of a bug rather than a feature request. I never intended to remove those icons, seems like one of my 0Harmony methods stopped it. Will work on fixing this.

**Comment by DubyaDude** [comment]
This seemed to be a quick one-liner fix. Fix has just been implimented

~Thank you for using Ruby
