### ISSUE TITLE
Designer: per-user custimization

### ISSUE THREAD

**Issue by untuned** [DubyaDude/RubyClientPublic#28]
Set a custom nameplate/name color for a specific user.

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Designer] Nameplate Colors](https://trello.com/c/AyeYqrq8/41-designer-nameplate-colors)

**Comment by untuned** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [[Designer] Nameplate Colors](https://trello.com/c/AyeYqrq8/41-designer-nameplate-colors)

Does that mean it's in progress? I can't view the board.

**Comment by DubyaDude** [comment]
> > ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [[Designer] Nameplate Colors](https://trello.com/c/AyeYqrq8/41-designer-nameplate-colors)
> 
> Does that mean it's in progress? I can't view the board.

Trello page is currently private until further notice
