### ISSUE TITLE
Block by avatar

### ISSUE THREAD

**Issue by jaxjaxk** [DubyaDude/RubyClientPublic#29]
A feature so that you can block an avatar. This why you can automatically block obnoxious avatars no matter who uses it anytime someone puts on that specific avatar.

**Comment by DubyaDude** [comment]
Also tagging onto this suggestions, hiding by avatar authors. Though I wouldn't do blocking, I'll do avatar hiding (as that's what I believe what you meant in the first place)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Avatar] Hiding by AvatarID/AuthorID](https://trello.com/c/a5ksAjJ9/82-avatar-hiding-by-avatarid-authorid)
