### ISSUE TITLE
Search Avatars

### ISSUE THREAD

**Issue by unsolidsnake** [DubyaDude/RubyClientPublic#31]
Search by avatar names like vrctools allow you to do

**Comment by Murkur** [comment]
last time I heard this was a planned feature in collaboration with FrostByte thats whenever an avatar database can be setup

**Comment by DubyaDude** [comment]
I now own the database, so it's a solo project now, working on getting a better host since it's a lot of information to hold. I will be working on this though once the Unity 2018 version of Ruby is finally done

**Comment by Murkur** [comment]
aye thanks for the info dubbya ❤️

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Avatar] Avatar Search](https://trello.com/c/3iaYLEez/83-avatar-avatar-search)
