### ISSUE TITLE
Adding an Alarm System to Ruby.

### ISSUE THREAD

**Issue by MsRosetta** [DubyaDude/RubyClientPublic#33]
I like to sleep in vr a lot, and often I don't wake up to my phones alarm. A system for an alarm would be amazing as a separate module. My girlfriend would also like this. It would be amaaazzinggg

**Comment by MsRosetta** [comment]
Idk how to add a label I dont use github sorrryyy

**Comment by KortyBoi** [comment]
The latest version of OpenVR Advanced Settings has a built-in **[Simple Alarm Clock](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#features)** feature.
You can download it here: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases

**Comment by Janni9009** [comment]
Its messy and doesnt work half the time (at the least).
It was already there and broken in 3.X @KortyBoi

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Base] Alarms](https://trello.com/c/Zr4RjaHQ/84-base-alarms)
