### ISSUE TITLE
Console 'Time/Clock'

### ISSUE THREAD

**Issue by MrTQRNapart** [DubyaDude/RubyClientPublic#38]
In the Console, I want to be able to see a local time next to events, E.g WHen someone leaves it says what time they left etc

**Comment by DubyaDude** [comment]
This has been implemented in VRC-2018 version of Ruby (still in the works).
I'll leave this open until that's officially released

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Internal] Console Timestamp](https://trello.com/c/UNfAQtdL/86-internal-console-timestamp)

**Comment by DubyaDude** [comment]
This was released in Ruby v4.0.0
