### ISSUE TITLE
Remove certain Categories/Tabs

### ISSUE THREAD

**Issue by MrTQRNapart** [DubyaDude/RubyClientPublic#39]
The ability to Show or Hide world types and avatar lists, e.g Hide the Public, Legacy Avatars and Hide 'Active my platform' world category. Would be nice to just only see Favourited avatars, Local Favourites and Personal Avatars etc

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Designer] Removing rows from Worlds list/Avatars list](https://trello.com/c/HMvxipIA/87-designer-removing-rows-from-worlds-list-avatars-list)
