### ISSUE TITLE
Known Yoinkers don't always get a black nameplate

### ISSUE THREAD

**Issue by ddakebono** [DubyaDude/RubyClientPublic#4]
On multiple occasions now I've come across someone who's listed in bully hunters, but their nameplate doesn't get set to black.

One such user I came across is [NOPE]

**Comment by DubyaDude** [comment]
Currently, black nametags are not synced with bully-hunters. It only makes the nametag black if you see them in a lobby with you.

Moved to suggestion in base: Syncing Black-Nametags with bully-huntersvx

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Base] Yoinker Detector](https://trello.com/c/KDQZCfk3/8-base-yoinker-detector)

**Comment by DubyaDude** [comment]
Closing because of no intention of bringing this feature back, explained further in https://github.com/DubyaDude/RubyClientPublic/issues/15#issuecomment-752645548
