### ISSUE TITLE
Spoof offline mode

### ISSUE THREAD

**Issue by ShiroBlank** [DubyaDude/RubyClientPublic#40]
An ability to spoof being offline so that people cannot join me and bother me.

**Comment by GhostYiL** [comment]
Dubya already have code for that, it just a matter of time.

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Base] Current World Spoofer](https://trello.com/c/INmHVYdF/88-base-current-world-spoofer)

**Comment by DubyaDude** [comment]
Has been shown to be pretty risky, and with VRChat's new statuses, seems a bit useless.
If you feel otherwise re-open and throw up a good debate
