### ISSUE TITLE
"Last users" row in social

### ISSUE THREAD

**Issue by Bluscream** [DubyaDude/RubyClientPublic#41]
A new row within the social tab of the menu that shows the last 60 or so users that disconnect from the lobbies that you were in. To add the person you talked with but he crashed or whatever reason :)

**Comment by LucianUsagi** [comment]
"Recently Seen" or "Recent" or something more easily understood perhaps

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Unknown] Recently Seen Users](https://trello.com/c/ZKTCNA6c/89-unknown-recently-seen-users)

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/75325062-6f02dd80-5878-11ea-940c-4ee3a93c5e7d.png)

🤔

**Comment by DubyaDude** [comment]
![Screenshot_20200226-120723](https://user-images.githubusercontent.com/13679909/75368982-9a91c200-5890-11ea-97db-3ea404c80fe3.png)
🤔

**Comment by Bluscream** [comment]
I c
