### ISSUE TITLE
Portal notifyer

### ISSUE THREAD

**Issue by Myrkie** [DubyaDude/RubyClientPublic#42]
Add notifications that a portal has been placed somewhere in the world aswell as an option to teleport to its location

Suggested tags (ruby base)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Base] Overall Portal Drop Notifier](https://trello.com/c/AAUjIcEE/90-base-overall-portal-drop-notifier)

**Comment by Murkur** [comment]
closed as its on trello in plans

**Comment by DubyaDude** [comment]
Pliz no close ty

**Comment by DubyaDude** [comment]
Merging with https://github.com/DubyaDude/RubyClientPublic/issues/45 and moving it to Moderation
