### ISSUE TITLE
Higher Resolution Pictures/Camera Module

### ISSUE THREAD

**Issue by RawPotatoChip** [DubyaDude/RubyClientPublic#43]
Add a module to export higher resolution photos from VRC with options to switch between 1080p (standard) and 2k, 4k etc...

(suggested tags: type:suggestion)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Unknown] Camera Improvements](https://trello.com/c/ERf3MY2N/93-unknown-camera-improvements)
