### ISSUE TITLE
[Suggestion] Add delay for eventshield on instance join

### ISSUE THREAD

**Issue by MinerSpark** [DubyaDude/RubyClientPublic#44]
When joining a world like Wulfies hang out & sleep or Sleep rooms that have hidden parts, they are shown at spawn and hidden on join, if you're not the instance owner that doesn't happen so you're loading more then you can see lowering fps.

Possible add a delay to the eventshield when joining a instance which is toggleable so if you want it or not, it can be optional.

**Comment by DubyaDude** [comment]
Since this currently does not exist post IL2CPP, closing issue
