### ISSUE TITLE
Portal logger

### ISSUE THREAD

**Issue by Murkur** [DubyaDude/RubyClientPublic#45]
Log were a portals world info like the history module without needing to enter it so you dont have to worry about missing a portal drop

suggested tags (item:worlds)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Worlds] Portal Drop History](https://trello.com/c/SCH8lUSG/91-worlds-portal-drop-history)

**Comment by DubyaDude** [comment]
Pliz no close ty

**Comment by DubyaDude** [comment]
Merged with https://github.com/DubyaDude/RubyClientPublic/issues/42
