### ISSUE TITLE
Suggestion: Full Shader Blocker

### ISSUE THREAD

**Issue by Kamiesio** [DubyaDude/RubyClientPublic#49]
Have a full shader blocker that even blocks your avatar from users that want to force change your avatar into a Toxic/Crasher Type of avatar

**Comment by Bluscream** [comment]
How are these two connections connected?

Also ruby already contains a force avatar change patch

**Comment by DubyaDude** [comment]
I just fixed the last known method of force avatar changing in Ruby, be sure you have VRCEventShield on. Otherwise, I'm not into the whole *shader block* idea.
