### ISSUE TITLE
In game UI keyboard replacement 

### ISSUE THREAD

**Issue by Myrkie** [DubyaDude/RubyClientPublic#5]
An option to change VRChats UI keyboard to a better alternative like the one provided by OVRTOOLKIT (which has a Keyboard SDK for custom keyboard layouts and is made in unity using UI panels)

Suggested tags (item:base type:suggestion)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Designer] UI keyboard replacement](https://trello.com/c/ulcpKJpt/67-designer-ui-keyboard-replacement)
