### ISSUE TITLE
ESP Colors

### ISSUE THREAD

**Issue by MintLily** [DubyaDude/RubyClientPublic#51]
Add ESP Colors by nameplate color.
If nameplate of rank color is #2BCF5CFF then Player ESP is #2BCF5CFF
same colors would merge with other ESP capsules, whereas different colors would overlap.

**Comment by DubyaDude** [comment]
ESP capsule color is a static variable, meaning changing it for one object changes it for everything.
Hence
Not possible

**Comment by DubyaDude** [comment]
I stand corrected
