### ISSUE TITLE
Force avatars onto users LOCALLY

### ISSUE THREAD

**Issue by OptoCloud** [DubyaDude/RubyClientPublic#52]
It whould be really nice to have a feature where you can locally force an avatar onto someone, or some other solution that allows someone to show for you as an avatar that other people in the world might not appreciate.
Ex:
the world ur in only allows green avatars, but u and ur friend still want to show up as ur regular avatars.

**Comment by DubyaDude** [comment]
Sorry, don't quite understand what the suggestion is here

**Comment by OptoCloud** [comment]
@DubyaDude So ur in a world where the owners of the world only allow you to be in a certain avatar, but you and ur friend want to see each others as your normal avatars so if u could force an avatar onto another user (locally) that whould be great.

**Comment by DubyaDude** [comment]
If we were still on local IK this could be reasonably done, however, its NetIK making this extremely difficult to pull off

**Comment by OptoCloud** [comment]
welp :c
