### ISSUE TITLE
Block kicker

### ISSUE THREAD

**Issue by jaxjaxk** [DubyaDude/RubyClientPublic#55]
The option makes it so when the world owner try’s to kick you it blocks them in response. This gives the illusion that you were in fact kicked to them.

**Comment by AtiLion** [comment]
There's a kick and block for a reason, if you are being annoying to everyone and not just the owner then the owner can kick you out, if you are being annoying only to the owner then they will most likely just kick you. Anti-Kick is highly malicious and extremely toxic so I doubt this will ever be added to Ruby.

**Comment by jerk** [comment]
That's not a very good idea. The owner tries to kick you for a reason, there's already a anti-kick, closing this.
