### ISSUE TITLE
Malicious List

### ISSUE THREAD

**Issue by SleepVR6** [DubyaDude/RubyClientPublic#59]
As Ruby has the ability to log and mark people who are rippers, is it possible to make one for people who send Uspeak packets and use RAM laggers?
Highlight/Change their nameplate so people can know who to avoid/block.

**Comment by RubyYuukoShionji** [comment]
Would it be possible yes, but in my opinion it wouldn't be smart to do so as it could potentially open up to certain legal headaches down the road (there is a HUGE difference between notifying of an event when it happened and hanging an user out for something they have done in the past). Ruby already protects from all known ram laggers so you wouldn't gain any extra protection from it.

But that's just my two cents

**Comment by jerk** [comment]
VRChat has already fixed the Uspeak issue and we are unlikely to ever add it, closing this. (I've already talked to dubya once about this in the past.)
