### ISSUE TITLE
Add avatar name next to avatar ID

### ISSUE THREAD

**Issue by Murkur** [DubyaDude/RubyClientPublic#6]
Add the avatars name next to the avatars ID in Ruby Avatar for avatar history and avatar favorites

Suggested tags (item:avatar type:suggestion)

**Comment by DubyaDude** [comment]
Clarification: in the actual txt files

**Comment by Murkur** [comment]
yes in the text files created by the modules
Avatar-Favorites.txt
Avatar-History.txt

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Avatar] Local Favorites](https://trello.com/c/G2DI9Erv/44-avatar-local-favorites)

**Comment by Murkur** [comment]
closing because old mono days and has been done in IL2CPP
