### ISSUE TITLE
Selective Personal Space

### ISSUE THREAD

**Issue by EatmysmokeRDZ** [DubyaDude/RubyClientPublic#61]
Allow a Ruby user to set personal space on a per user basis would be very useful and appreciated.

~WeirdBlueDragon~

**Comment by DubyaDude** [comment]
Define safe space?

**Comment by Shanpai** [comment]
probably talking about personal space

**Comment by EatmysmokeRDZ** [comment]
Personal space* Sorry suggestion edited.
