### ISSUE TITLE
Custome made emojis or like a Keyboard/pen

### ISSUE THREAD

**Issue by katzina00** [DubyaDude/RubyClientPublic#62]
Keyboard and pen Which only you can use. But everyone can see. Like, if you want to type and not talk. Could be fun.

Or Maybe like.. voice changer. Would Also be pretty  damn cool :). 
Custome emojis like.. The Ruby logo or like.. WoW! GG! UR COOL! Stuff like that. Could Have been pretty fun :) Insteed of the boring one in vrchat.

**Comment by Janni9009** [comment]
While you can globally instantiate custom objects (or at least could in the last update); everyone would have to use the mod to see these objects. So the pen/emotes would be possible, but only for other Ruby users (or if this feature if at all made, would be made standalone as well, maybe even raw melonloader users could use it together with ruby users)
