### ISSUE TITLE
Color changing capsules. 

### ISSUE THREAD

**Issue by KittensScythe** [DubyaDude/RubyClientPublic#65]
saw this in another mod that makes the selection outlines change color for object interaction and esp capsules, looks really nice in-game and would love to see it in ruby
pretty much was rainbow cycle of colors, but actually looks real nice ingame

**Comment by DubyaDude** [comment]
Already suggested in https://github.com/DubyaDude/RubyClientPublic/issues/51
We already have the base concept of this done, however, we need to fix some issues with avatars over rendering before release.
