### ISSUE TITLE
Toggle Shader name tags

### ISSUE THREAD

**Issue by Myrkie** [DubyaDude/RubyClientPublic#67]
Make it so that toggling nametags in vrchat will also disable custom nametag shaders like Mochies nametag shader

[suggested tags: type:suggestion item:base]

**Comment by RubyYuukoShionji** [comment]
Vrchat actually implemented a random offset on the name tags now to counter these. Unless you want to disable this random offset for them to be once again useable locally?

**Comment by Murkur** [comment]
yeah I forgot I made this post but that random offset is probably the most useless update ive ever seen so yeah would really like an option to disable that offset
