### ISSUE TITLE
Console log does not log to a text file. 

### ISSUE THREAD

**Issue by aspyhackr** [DubyaDude/RubyClientPublic#68]
I would like an option to log the console to a text file, perhaps a single rolling txt file, or possibly the last 3 openings of VRC. I'd like to be able to see who was in the VRC world with me after I crash.  [suggested tags: type:suggestion item:moderation]

**Comment by DubyaDude** [comment]
Hmmm, only thing I'd change is to assign it to base since other modules would find it helpful as well

**Comment by DubyaDude** [comment]
Closing. will be added to next major ruby update (this weekend)
