### ISSUE TITLE
Updated compiled yoinker list

### ISSUE THREAD

**Issue by ripxfrostbite** [DubyaDude/RubyClientPublic#7]
If possible it would be nice to get a newer compiled list, the last is from June, and lacks alot of users.
Not sure if many others use it, but I merge it into a watchlist a tool I develop uses.

Suggested tags (item:discord type:suggestion)

**Comment by DubyaDude** [comment]
I've decided not to do this as I'm planning on making a global 'list' of Yoinkers that YoinkerDetector will sync with ( covered in issue #4 )
