### ISSUE TITLE
The ruby gem on people's name

### ISSUE THREAD

**Issue by katzina00** [DubyaDude/RubyClientPublic#71]
Like.. ok.. So uhm.. How to explain..

Where people see other peoples name.. there could be a lil Ruby mark. So everyone who got the Ruby, can easly see other people with Ruby. By seeing a Ruby gem.. if it makes sence..

**Comment by Nekromateion** [comment]
Dubya said many times before that that won't be implemented.

**Comment by DubyaDude** [comment]
as @Nekromateion stated, I refuse implementing such features for privacy and anonymity reasons
