### ISSUE TITLE
FPS CAP Unlocker 

### ISSUE THREAD

**Issue by EvilJason123** [DubyaDude/RubyClientPublic#75]
i think ruby client should have a FPS unlocker . cant really stand some worlds just goes down to 20 fps quickly , even though the game shouldn't have put its cap to 90 fps . 
i suggest that ruby client would have a fps unlocker that uncaps the limit to 300 fps . would probably help too .
cause when ruby was down i decided to use melon loader for abit but than i stumble upon a mod that uncaps fps for vrchat . so im like " hmmm  why dont ruby have a FPS uncapper" . i think it be a great mod to have . 
-BuddyJason

**Comment by snake587587** [comment]
you realize if your fps goes down to 20 in a world that's just you I don't think worlds can limit fps its only performance from your pc

**Comment by EvilJason123** [comment]
> you realize if your fps goes down to 20 in a world that's just you I don't think worlds can limit fps its only performance from your pc

no its defo not my pc cuz if it was my pc i would have gotten a new one . why would i need a shitty game like vrchat that doesnt uncap its frames . like bruh  dont @ me nowadays people cant even optimize their world properly.

**Comment by Janni9009** [comment]
I mean there is a 45fps cap applied by oculus and steamVR in certain circumstances to remain stable without constantly dropping frames (which is worse than a low framerate as you percieve lag). In fact framerate while in VR cannot be set using unity's target framerate as its managed by your VR software from what i've seen so far. Also you wouldnt want uncapped frames (beyond refresh) anyways, screen tearing in VR is really, really bad.

**Comment by CryCry34** [comment]
Uncapping fps won't help keep your fps up, 
however it will surely minimize noticeable stutters and latency.
Would be nice to add a config to set max fps and unfocused fps.
