### ISSUE TITLE
Bring Back Post Processing toggles

### ISSUE THREAD

**Issue by MintLily** [DubyaDude/RubyClientPublic#76]
Back on Ruby v3, there was an option to remove the world **Post Processing Volumes**.
I would like to bring it back, for I have noticed that some worlds don't have toggles for **PP**.
If you can do this, please add common types to toggle:
**Bloom, Chromatic Abberation, Ambient Occlusion**
Have them turn off, and restore them. Just as _SetGameObjectActive_

**Comment by ChillPenguinVR** [comment]
I would love to be able to toggle bloom.
