### ISSUE TITLE
Leave on X Join

### ISSUE THREAD

**Issue by KuwuroUsagi** [DubyaDude/RubyClientPublic#8]
An editable list that accepts user ids(or avatar ids?). Can be stored via json.

If one of the user/avatar ids joins a world you're, in you get sent home. 
This functions as a decent temporary measure against creeps, stalkers, crashers, world clappers or what have you.

**Comment by Murkur** [comment]
you may beable to get this merged with "auto disconnect when a mod joins" as its the same concept

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Moderation] Leave on X join](https://trello.com/c/NyOku7u6/66-moderation-leave-on-x-join)
