### ISSUE TITLE
[Feature Request] Moderation Sounds / HUD Customization (+Improvements?)

### ISSUE THREAD

**Issue by JewBoii** [DubyaDude/RubyClientPublic#80]
- Would be interesting to add join/exit lobby noises for any hud-enabled notifications involving joining/leaving the lobby similar to Join Notifier (makes it easier to know when friends join and stuff).

- Perhaps add a time selector for how long specific notifications come up for on the HUD as well.

- Allow users to customize where the hud notifications pop up so we can move them off the center of the screen and down to the bottom left like Join Notifier has, or bottom right/top right/top left. Any corner notifications would stack vertically to allow more on screen at a time to prevent hud flood (obviously these would be smaller notifications to avoid vr users getting a massive portion of their screen covered)

- Allow users to customize the color of the notifications in specific use cases of the world being the same color as the notification, making it tough to read in VR.

A lot of these are similar to Join Notifier, as I cannot use that mod anymore as it crashes my vrchat but I really enjoyed their layout and would be neat to see something similar here to give more presence to the notifications.

**Comment by RubyYuukoShionji** [comment]
This seems like it would be better suited to be split up into multiple suggestions. Please split it up.

> * Perhaps add a time selector for how long specific notifications come up for on the HUD as well.
#99
