### ISSUE TITLE
Option to remove portal drops from console

### ISSUE THREAD

**Issue by MinerSpark** [DubyaDude/RubyClientPublic#82]
Add an Option to remove portal drops from console but keep them in log if possible.

The "antiportals, spawned to close for when people put you on portal kos kinda thing, not the portaldropper id"

**Comment by DubyaDude** [comment]
Fixed bug with AntiPortal still showing on HUD if HUD messages are disabled, but, will be working on a dedicated button for AntiPortal notifs
