### ISSUE TITLE
Auto Login For VRchat User Auth

### ISSUE THREAD

**Issue by SpacersVIP** [DubyaDude/RubyClientPublic#87]

**Comment by Shanpai** [comment]
wait, once you sign in vrchat with the user auth
you dont have to do it again...

**Comment by DaytonaX2** [comment]
Most of the time if you are logged out its because you swapped ips or changed your password recently or other stuff.

**Comment by SpacersVIP** [comment]
when you go on a vpn it logs you out

**Comment by Murkur** [comment]
it happens because vrchat ties your authcookie to IPV4 and it not changeable between ips https://feedback.vrchat.com/feature-requests/p/allow-authcookie-to-be-used-from-a-different-ip-address-extra-features

**Comment by SpacersVIP** [comment]
Murkur what if you had a button like the old times where it logs you login to a .txt are .json and there is a button on the login screen completely removing the ipv4 limitations that vrchat has in place

**Comment by Murkur** [comment]
its possible never said it wasnt as it used to be a mod for vrc mod manager

**Comment by jerk** [comment]
Auto login? be more specific, user auth in as what

**Comment by SpacersVIP** [comment]
kronik like the old days so on the login page it will say login with last credentials aka username;password
