### ISSUE TITLE
[Feature Request] Hud UI Color Customization

### ISSUE THREAD

**Issue by TarynBear** [DubyaDude/RubyClientPublic#89]
I'd love to have the ability change the color of the hud. It'd make the game a lot more enjoyable to look at when i have to go into my hud. Maybe a rainbow option that makes the hud constantly change colors!

**Comment by Janni9009** [comment]
If by HUD you mean the QuickMenu and UI, then that would be the currently still in rewriting Designer module.
Rainbow color would be quite intense and lag your game down to single digit frames, or at least below a playable framerate in general though considering we are talking about a few hundred objects here.

**Comment by TarynBear** [comment]
> If by HUD you mean the QuickMenu and UI, then that would be the currently still in rewriting Designer module.
> Rainbow color would be quite intense and lag your game down to single digit frames, or at least below a playable framerate in general though considering we are talking about a few hundred objects here.

The menu that pops up when you press ESC. I don't know all the terms for that stuff. But I've seen a few video with clients that offer changing the color of that menu and making it rainbow and they didnt have any FPS lag at all.

**Comment by Murkur** [comment]
The Small menu that appears when you press escape its called the Quick Menu as janni said Ruby already has a module to change this but its currently still being developed for IL2CPP as for the rainbow part I cant comment on that as ive never seen that before.

**Comment by TarynBear** [comment]
> The Small menu that appears when you press escape its called the Quick Menu as janni said Ruby already has a module to change this but its currently still being developed for IL2CPP as for the rainbow part I cant comment on that as ive never seen that before.

Ah okay. I don't know all the terms or understand what a lot of this is but thanks for the information.

**Comment by Murkur** [comment]
The changing of quick menu colors is present in the Designer module but like stated above it has yet to be updated you can view status of other modules on [RubyV4 trello](https://trello.com/b/PnmNr8jj/rubyclient-v40)

**Comment by TarynBear** [comment]
> The changing of quick menu colors is present in the Designer module but like stated above it has yet to be updated you can view status of other modules on [RubyV4 trello](https://trello.com/b/PnmNr8jj/rubyclient-v40)

Thank you!

**Comment by RubyYuukoShionji** [comment]
Closing as this is literally designer modules job.
