### ISSUE TITLE
Best Friend System

### ISSUE THREAD

**Issue by KuwuroUsagi** [DubyaDude/RubyClientPublic#9]
Editable file, probably stored via json for "best friend" user ids.
If a specified user logs onto vrchat a hud notification (a la the moderation module) appears letting you know they've come online (bonus points for an additional button on someones profile to autoadd them to best friends list)

**Comment by DubyaDude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Unknown] 'Best Friend' system](https://trello.com/c/Bp8GDLTy/80-unknown-best-friend-system)
