### ISSUE TITLE
World Host Indicator

### ISSUE THREAD

**Issue by DydyRev** [DubyaDude/RubyClientPublic#94]
Add a world host indicator so we know who's hosting

**Comment by RubyYuukoShionji** [comment]
Could you please give an example of when knowing who's the room master would be useful? I'm not against adding it just cannot think of a reason to justify it myself.

**Comment by DydyRev** [comment]
well I join a lot of drinking nights so its helpful to know who the host is sometimes because certain buttons can only be activated by the host of the instance

**Comment by Janni9009** [comment]
Game worlds that have a master reset (ex. murder) to know who to kick if the instance master is abusing it/who to shout at when the game is janked up.

**Comment by jerk** [comment]
Knowing the room master could give you the potential answer to know why the room is locked. (Event syncing)
