### ISSUE TITLE
Mute self for select players.

### ISSUE THREAD

**Issue by Janni9009** [DubyaDude/RubyClientPublic#95]
Apparently its possible to mute yourself for only select users (might be a partial block?) , and if possible to be added I'd like to find this functionality in Ruby as well. It could be useful in protective cases when takjug to friends in public worlds without wanting the usual random plebian to make an unwanted comment or crash you for your political stance (okay that last one isnt serious but you get the point).

**Comment by RubyYuukoShionji** [comment]
Interesting suggestion, however in the use cases you point out it seems like a whitelist rather then a blacklist would be more beneficial. Of course both could be implemented, but I'm wondering if you had any usage case where a blacklist(selectively mute) rather then a white list (mute by default when on, then select who can hear you) would be beneficial.

**Comment by Janni9009** [comment]
Ah, yes, a whitlist was what i meant but didnt describe properly enough. (blame my non-existant sleep schedule)
Not sure how a blacklist could be used other than properly soft-blocking in games so you can still see their avatar to still interact with them but neither side has to hear each other? I'm certain someone would find use for a blacklist. ¯\_(ツ)_/¯
