### ISSUE TITLE
Add jump strength modifier 

### ISSUE THREAD

**Issue by Janni9009** [DubyaDude/RubyClientPublic#96]
Should be pretty simple to do in theory, all thats really needed for this is getting the local VRCPlayer instance, then on it the LocomotionInputController component, and in that, the jumpImpulse field and setting it to any float, like with run/strafe/walk speed. From what i see with ML its not (longer) obfuscated either, might be private/internal though.

**Comment by DubyaDude** [comment]
This is now in Movement Module.
